import React from 'react';
import { APP_DATA } from '../data/mockData';

export const Footer: React.FC = () => {
    return (
        <footer className="bg-surface-container-low w-full py-20 border-t border-outline-variant/10">
            <div className="max-w-7xl mx-auto px-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-12 items-start mb-16">
                    {/* Logo & Description */}
                    <div className="flex flex-col gap-6">
                        <img src={APP_DATA.navigation.logo} alt="Oxxy Logo" className="h-10 md:h-12 w-auto object-contain self-start" />
                        <p className="text-on-surface-variant text-sm leading-relaxed max-w-xs font-medium">
                            Providing transparent, high-quality, and affordable AI-driven healthcare solutions to 1.3 billion Indians.
                        </p>
                    </div>


                    <div className="flex flex-col gap-6">
                        <h4 className="font-black text-xs text-secondary uppercase tracking-widest">Quick Navigation</h4>
                        <div className="flex flex-wrap gap-x-8 gap-y-4 font-bold text-xs uppercase tracking-widest">
                            <a href="https://www.oxxy.in/health_report/scan.php" className="text-on-surface-variant/70 hover:text-primary transition-colors" target="_blank" rel="noopener noreferrer">AI Health Scan</a>
                            <a href="#faq" className="text-on-surface-variant/70 hover:text-primary transition-colors">FAQ</a>
                            <a href="https://www.oxxy.in/about-us" className="text-on-surface-variant/70 hover:text-primary transition-colors" target="_blank" rel="noopener noreferrer">About Us</a>
                            <a href="https://www.oxxy.in/contact-us" className="text-on-surface-variant/70 hover:text-primary transition-colors" target="_blank" rel="noopener noreferrer">Contact</a>
                        </div>
                    </div>
                </div>

                {/* Legal Disclaimer Box */}
                <div className="mb-12 p-10 bg-[#023350] rounded-[2.5rem] border border-primary/20 text-white shadow-2xl relative overflow-hidden group">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full translate-x-1/4 -translate-y-1/4 blur-3xl group-hover:bg-primary/10 transition-colors" />
                    <div className="relative z-10">
                        <span className="text-primary font-black inline-flex items-center gap-3 mb-6 uppercase tracking-[0.3em] text-[10px] bg-white/10 px-4 py-2 rounded-full">
                            <span className="material-symbols-outlined text-sm">warning</span>
                            Oxxy Medical Disclaimer
                        </span>
                        <p className="text-white/80 text-xs md:text-sm font-medium leading-relaxed italic">
                            The Oxxy AI Health Scan is a wellness assessment tool designed to provide general health insights and is <span className="text-primary font-bold">not a substitute for professional medical advice, clinical diagnosis, or specialized treatment.</span> The results generated by our AI mapping technology should not be used as the sole basis for making medical decisions. Always consult with a licensed physician or a qualified healthcare professional regarding any medical concerns or conditions. In the event of a medical emergency, please contact your local emergency services immediately. Oxxy accepts no liability for decisions made based on AI output.
                        </p>
                    </div>
                </div>

                {/* Bottom Bar */}
                <div className="pt-8 border-t border-outline-variant/10 flex flex-col items-center gap-4 text-on-surface-variant/60 text-[10px] font-bold uppercase tracking-widest text-center">
                    <p>© {new Date().getFullYear()} Oxxy Healthcare. All rights reserved.</p>
                </div>
            </div>
        </footer>
    );
};
