export const APP_DATA = {
  navigation: {
    logo: "https://www.oxxy.in/image/oxxy_logo.png",
    name: "Oxxy",
    links: [
      { label: "Face Scan", href: "#face-scan", active: true },
      { label: "Health Plans", href: "#health-plans", active: false },
      { label: "FAQ", href: "#faq", active: false }
    ]
  },
  hero: {
    title: "AI Health Scan by Oxxy — Your Face Tells a Story.",
    description: "Take a free 30-second AI health scan. Our transdermal optical imaging technology analyzes 10,000+ data points to provide a clinical-grade health snapshot instantly.",
    cta: "Start My Oxxy AI Scan — Free",
    stats: "Used by 2,00,000+ Indians across 1,500 cities.",
    features: [
      { icon: "verified_user", text: "ISO Certified Tech" },
      { icon: "lock", text: "HIPAA Compliant" },
      { icon: "timer", text: "Results in 30 seconds" }
    ]
  },
  problem: {
    title: "Most Indians don't know they're at risk.",
    description: "Lifestyle diseases account for 68% of all urban deaths. Early detection is not just a choice—it's a necessity. Oxxy provides the early warning system your body deserves.",
    stats: [
      { value: "₹2,40,000", description: "Average annual out-of-pocket health expense for a family of four in metro cities." },
      { value: "68%", description: "Of lifestyle diseases in urban India remain undiagnosed until critical stages." },
      { value: "1 in 3", description: "Adults suffer from chronic stress-induced fatigue that Oxxy AI can detect via facial micro-expressions." }
    ]
  },
  howItWorks: {
    title: "Three steps to health clarity.",
    steps: [
      { icon: "photo_camera", title: "1. Scan & Map", description: "Allow camera access. Our AI maps 400+ facial bio-markers and skin perfusion points." },
      { icon: "psychology", title: "2. Neural Analysis", description: "The Oxxy engine analyzes pulse, HRV, and stress markers using transdermal imaging." },
      { icon: "analytics", title: "3. Diagnostic Snapshot", description: "Receive a detailed report including BP, BMI, and Life Expectancy instantly." }
    ]
  },
  scanModule: {
    title: "Oxxy AI Analyzing Vital Markers...",
    initialProgress: 65,
    statusText: "Ready to Scan",
    previewImage: "/oxxy_scan.png",
    results: [
      { label: "Pulse Rate", value: "79 bpm", status: "Normal", color: "tertiary" },
      { label: "Blood Pressure", value: "116/80", status: "Normal", color: "tertiary" },
      { label: "Stress Index", value: "5/10", status: "Controlled", color: "primary" },
      { label: "BMI Index", value: "25", status: "Overweight", color: "error" },
      { label: "Breathing Rate", value: "15/min", status: "Normal", color: "tertiary" },
      { label: "Cardiac Workload", value: "175", status: "Slightly High", color: "primary" },
      { label: "Recovery Index", value: "61%", status: "Good", color: "tertiary" },
      { label: "Life Expectancy", value: "76 yrs", status: "Projected", color: "secondary" }
    ],
    recommendation: {
      text: "Based on your Oxxy scan, your <span className=\"text-primary font-bold\">Cardiac Workload</span> is elevated. We recommend the <span className=\"font-bold\">Oxxy Vitality Shield</span> with integrated cardio-health checkups.",
      cta: "Get My Oxxy Plan — First Month 50% Off"
    },
    disclaimer: {
        short: "Oxxy AI Suggestion: Not a medical diagnosis.",
        full: "LEGAL DISCLAIMER: AI scan results are generated by Oxxy AI for informational purposes only. Oxxy is not a certified diagnostic laboratory. These findings are health suggestions, not medical conclusions."
    }
  },
  depth: {
      title: "The Science of Oxxy AI",
      description: "Our proprietary technology utilizes Transdermal Optical Imaging (TOI) to extract blood flow information from the face.",
      features: [
          { title: "Remote PPG", description: "Detection of blood volume pulse through the camera lens without physical contact." },
          { title: "Neural Biometrics", description: "Processing 10,000+ data points per second to identify micro-stress signals." },
          { title: "Diagnostic Accuracy", description: "Our algorithms are trained on 1M+ clinical data points to ensure 92% correlation with clinical vitals." }
      ]
  },
  pricing: {
      title: "Regional Assessment Pricing",
      regions: [
          { name: "Delhi NCR", cost: "Free", value: "₹10,000", badge: "Live" },
          { name: "Mumbai, Bangalore, Pune", cost: "₹100", value: "₹10,000", badge: "Limited" }
      ]
  },
  socialProof: {
    title: "Voices of Oxxy Users.",
    testimonials: [
      { name: "Rajeev S.", location: "Mumbai", rating: 5, quote: "\"The BP estimation was within 5% of my home monitor. Oxxy's tech is truly revolutionary for early detection.\"" },
      { name: "Priya M.", location: "Bangalore", rating: 5, quote: "\"It detected my high stress levels before I even realized I was burnt out. The plan they suggested is a lifesaver.\"" },
      { name: "Ankit T.", location: "Delhi", rating: 5, quote: "\"I never thought a face scan could estimate BMI and Life Expectancy. It's the depth of data that made me stay with Oxxy.\"" }
    ],
    partners: [
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCxXEIWc4YddQCEL5kgUc06X_lMVwk78aTOqQvXwo0aWHdqiDtm1nTi4lx6CfQCcTUCaUDW84iPNe4lLpnY3NQPpFco4yRj1VIs8dB_xl-HfwAXG5G3ZQpcE8LLF5SVsvsT4MvpCqN_Tcp_N8wnBO3OzUlGijzztlCX_-oMbs6QUvs5VT6lMSQrfWSr5GRiMNt3fYpTZTvYY3ixkpR2wmEnGiaw1zBEksVzZBzQazkrJ7NP6L4F5rTkkQptGIm0BE_N8g5FoxnzWs4",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCUyUxkIS1-_-MLCQwwMfTfI7VKyx5dM62jLUGMvWPpUfjaN4_br-rM_OuixI_iffotBUisvTM9E5-lGHtvLgOwCUk38meNWag7UpP9kgKI3pdeAbph8qQeyk_YikUXoMX_sRtltiW_aicWiLsGtpcC5g_O97PyX8lYeilZ9dVvqMkEaccnqcIoobSFuEyGWXAo7RGAhpDMfqfnecH-85NL4PGPW2wGFdLq5N59PL5j0j4EgrO-jwBUwBrnFuWWkUct9gmBQ7_3lM8",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBhi1OS8rRoO3u0eUuw6F89bnpoYJBRfV4M5FcrnvbuJlbVMSnp-RDsd41FFibmzRmkpQf8axZjZuRQ-a7nn7amH7JW8917faJhnOo3S6RdLLbNAwx6pm8kqEdlbkLe1iKPJnDsqP5fgNUUJk4bWMzdhC9LvJdCK5gYhEDp0Cx4FVjG-DthhmHobLSs4zGkOJdSjK3FgbB_C9l1hAIa8Kwg_JFPLUEZ9pSasTczamYi5Yhgn9Tiw2Qh6K_riBY80LVI5Wbbg0jVV0",
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCAxzC_qhDaK94zrtabRyk2bOkl-4dc7KN50MEKeeMsFL6hAcwwyjf_NrCuPTLfORGco6IxdSyXggQxBInvFkYjlBh8CB6pW-W-wOC-9x-MO1MpaMPM9DgSM18q7hRKamGHDTO95xt93Xc_5UhThbfCW8GDiLoLgjp8MIxUFrDVi4U4tCN-yS8XyFzQ9iLzHB33TtxKWw9T_UE16AkPmnJ4hKkHQLmSRyu-_rSav0U7hr5R6rz1OTz875KUPf2iCsZeGTpNxFEEgLc"
    ]
  },
  faq: {
    title: "Oxxy Member Questions.",
    questions: [
      { question: "How accurate is the Oxxy AI facial scan?", answer: "Our AI metrics have a 92-95% correlation with clinical-grade blood pressure cuffs and pulse oximeters when used in proper lighting." },
      { question: "Is my data private with Oxxy?", answer: "Yes. Oxxy follows HIPAA-compliant protocols. We do not store your video or images; only the extracted bio-marker data is used for your report." },
      { question: "Do I need to sign up for Oxxy before scanning?", answer: "No. You can perform the scan instantly. You only provide contact details if you wish to receive the full PDF report via email." },
      { question: "Can this replace a doctor's visit?", answer: "No. The Oxxy scan is a wellness monitoring tool designed for early detection. Always consult with a doctor for clinical diagnosis." },
      { question: "How do I claim the 50% Oxxy discount?", answer: "Upon completion of your scan, use the 'Get My Oxxy Plan' link to unlock your exclusive regional discount." }
    ]
  },
  footer: {
    cta: {
      title: "Join thousands who trust Oxxy for their health.",
      description: "Prevention starts with knowledge. Take the 30-second Oxxy AI scan now.",
      primaryAction: "Start My Oxxy AI Scan",
      secondaryAction: "Explore Oxxy Healthcare Plans"
    },
    navBar: {
      action: "Start Oxxy Scan",
      icon: "qr_code_scanner"
    }
  }
};
